### ISSUE TITLE
Allow to select custom branch name in web form for pre-releases

### ISSUE THREAD

**Issue by stonier** [ros-infrastructure/prerelease_website#14]
From a discussion on the ros release mailing list:

It would be incredibly useful to be able to specify a pre-release version on the [web page](http://prerelease.ros.org/create_job/hydro) as you make a test. Default value could be supplied from [source.yaml](https://github.com/ros/rosdistro/blob/master/hydro).

Right now I have to pull request if I want to test a different branch. 
Is it necessary to have a man in the middle for the process of specifying a version for a prerelease test?

**Comment by wjwwood** [comment]
Closed by https://github.com/ros-infrastructure/prerelease_website/pull/44
