### ISSUE TITLE
support entering repository information which are not in rosdistro

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/prerelease_website#38]
This would allow users to generate the prerelease command line for repositories which are not listed in the rosdistro yet. Currently they first need to add the repo with at least a source entry, wait for that to be merged, run the prerelease, and then do a bloom release. While they are iterating locally they are potentially already getting notification emails for the devel jobs from the farm (if not disabled explicitly. So this feature would drastically improve the workflow for users imo.

For each "external" repo the user has to provide:
* the repo name
* the scm type
* the repo url
* the version (branch / tag / hash)

The repository information is passed using the `--custom-repo` argument describe in https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/prerelease_jobs.rst#run-for-custom-repositories

This would also "solve" #14 since this feature would be a superset of what is requested there.

**Comment by wjwwood** [comment]
That sounds useful to me. It would also imply finally fixing https://github.com/ros-infrastructure/prerelease_website/issues/31. I don't have any spare cycles to do either right now. Maybe if I finish with my Lunar releases relatively quickly I can use some of my ROS 1 time for it.

**Comment by dirk-thomas** [comment]
Once this has been implemented the second part of [this](http://wiki.ros.org/action/diff/regression_tests?action=diff&rev1=61&rev2=62) recent wiki should be reverted and the option to specify external repos should be mentioned explicitly.

**Comment by 130s** [comment]
> the second part of [this](http://wiki.ros.org/action/diff/regression_tests?action=diff&rev1=61&rev2=62) recent wiki should be reverted

Yeah, I [noticed](https://github.com/ros-infrastructure/ros_buildfarm/issues/392#issuecomment-289095754) that my change wasn't accurate. I'll revert the "second" part.
