### ISSUE TITLE
[enhancement] support package format 3 (REP-149)

### ISSUE THREAD

**Issue by moriarty** [ros-infrastructure/prerelease_website#53]
I recently back-ported some things to Indigo and Kinetic, and the Indigo pull request job passed, so I released to Kinetic for the first time without running the pre-release job, and it failed.

Sorry- I didn't run the pre-release job- I had tested in Kinetic with my own docker :disappointed: 
[The Build Farm error](http://build.ros.org/view/Kdev/job/Kdev__fetch_gazebo__ubuntu_xenial_amd64/) I had was odd:
```
16:46:53 Traceback (most recent call last):
16:46:53   File "/usr/lib/python3/dist-packages/apt/cache.py", line 227, in __getitem__
16:46:53     return self._weakref[key]
16:46:53   File "/usr/lib/python3.5/weakref.py", line 131, in __getitem__
16:46:53     o = self.data[key]()
16:46:53 KeyError: 'ros-kinetic-catkin'
```
So I went to http://prerelease.ros.org/kinetic to run a proper test, and received the following error:

```
Error loading remote package list:
Error listing packages in remote repo 'fetch_gazebo': 
  'Unable to handle package.xml format version '3', please update catkin_pkg
  (e.g. on Ubuntu/Debian use:
    sudo apt-get update && sudo apt-get install --only-upgrade python-catkin-pkg)'
```

![pkg-format-3](https://user-images.githubusercontent.com/55676/55210055-e6c91380-51a2-11e9-8e3b-f2f63a9aac1b.png)

**Comment by moriarty** [comment]
Found a work-around in the [docs](http://wiki.ros.org/regression_tests#Customizing_prerelease_test_commands) without using the website:

`generate_prerelease_script.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml kinetic default ubuntu xenial amd64 fetch_gazebo --level 0 --output-dir ./`

And my pre-release job passes :confused:

**Comment by dirk-thomas** [comment]
@wjwwood Can you please update the server side to the latest releases. That should make this work right away.

**Comment by wjwwood** [comment]
Should be fixed.

**Comment by wjwwood** [comment]
<img width="1185" alt="Screen Shot 2019-04-28 at 10 01 59 PM" src="https://user-images.githubusercontent.com/100427/56877221-482e0d80-6a01-11e9-89e1-f9b8065eae8b.png">
